# Generated by Django 3.2.5 on 2021-07-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('url', models.CharField(blank=True, max_length=255)),
                ('action', models.IntegerField(choices=[(101, 'H5跳转'), (102, 'APK下载'), (103, '外部浏览器')], default=101)),
                ('status', models.IntegerField(choices=[(1, '开启'), (0, '关闭')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '轮播列表',
                'verbose_name_plural': '轮播列表',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('secret', models.CharField(max_length=255, unique=True)),
                ('username', models.CharField(blank=True, max_length=128, null=True, verbose_name='用户名')),
                ('avatar', models.CharField(blank=True, max_length=255, null=True, verbose_name='用户头像')),
            ],
            options={
                'verbose_name': '用户列表',
                'verbose_name_plural': '用户列表',
                'ordering': ['id'],
            },
        ),
    ]
